- op: replace
  path: /metadata/name
  value: golang-application

- op: replace
  path: /spec/template/spec/containers/0/name
  value: go-demo-app

- op: replace
  path: /spec/template/spec/containers/0/image
  value: c8n.io/waljaber/golang-app:prod-v1

- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 8080

# Memory, and CPU requests and limits.
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 50Mi

- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 50m

- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 512Mi

- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 500m

# Liveness and Readiness porbes
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
  value: 8080

- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/tcpSocket/port
  value: 8080

  