apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../../kustomize/base

namespace: golang-app-prod

commonLabels:
  app: golang-prod

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: deployment-template
  path: deployment-patch.yaml

- target:
    version: v1
    kind: Service
    name: service-template
  path: service-patch.yaml

- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: route-template
  path: route-patch.yaml