apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: {{.Values.appConfig.namespaceName}}
  name: {{ .Values.appConfig.name}}
  labels:
    app: {{ .Values.appConfig.label}}
    svc: {{ .Values.appConfig.label}}
spec:
  type: ClusterIP
  ports:
  - targetPort: {{ .Values.appConfig.deployment.containerPort}}
    name: {{ .Values.appConfig.service.portName}}
    port: {{ .Values.appConfig.deployment.containerPort}}
    protocol: TCP
  selector:
    app: {{ .Values.appConfig.label}}